Adding alt text to images
edgi-govdata-archiving/EEW-Website pull request #51
Opened 2020-09-12 20:35 UTC by lesliealanis

Im adding alt text to the images in the about page

2020-09-15 17:21 UTC, Frijol requested changes

2020-09-15 17:21 UTC, Frijol commented on content/about/about-content.md
> +[![ The David and Lucile Packard Foundation logo](./packard-logo.jpg)](https://www.packard.org/)
```suggestion
[![The David and Lucile Packard Foundation logo](./packard-logo.jpg)](https://www.packard.org/)
```

2020-09-17 02:45 UTC, lesliealanis commented
@Frijol I got rid of the space in this issue, how can I resolve the branch conflicts?

2020-09-17 17:26 UTC, Frijol commented
Here, I made you a quick demo! https://www.loom.com/share/a8c62f9cebbb4ab787c4ba495b6af9df

2020-09-27 19:38 UTC, Frijol approved these changes

2020-09-27 19:39 UTC, merged