Added alt text to the images
edgi-govdata-archiving/EEW-Website pull request #53
Opened 2020-09-13 03:18 UTC by lesliealanis

added descriptive text to the figma images, I'm not sure if its too descriptive and overwhelming so let me know.

2020-09-15 17:18 UTC, Frijol requested changes

2020-09-15 17:18 UTC, Frijol commented on content/reports/reports-content.md
> +![A graphic demonstrating the Senate Environment & Public Works Committee: eleven republican members and ten democrat members of the Senate Environment & Public Works Committee. John Barraso is a rep
```suggestion
![A graphic demonstrating the Senate Environment & Public Works Committee: eleven republican members and ten democrat members of the Senate Environment & Public Works Committee. John Barraso is a republican and the chair, Thomas R. Carper is a democrat and a ranking member](./senate-env-pw.png)
```

2020-09-15 17:18 UTC, Frijol commented on content/reports/reports-content.md
> +![A key to the colors used in the graphic: republicans are in red circles and democrats in blue circles, lighter shaded circles indicate the report card is yet to be made, darker shaded circles indic
```suggestion
![A key to the colors used in the graphic: republicans are in red circles and democrats in blue circles, lighter shaded circles indicate the report card is yet to be made, darker shaded circles indicate the report card is in progress, and circles with a green check indicate the report card is completed] (./key-outlines.png)
```

2020-09-15 17:18 UTC, Frijol commented on content/reports/reports-content.md
> +![A key to the markings used in the graphic: Committee chairs are circled in black, vice chairs are circled in a dotted black circle and ranking members have four black lines around them.](./key-prog
```suggestion
![A key to the markings used in the graphic: Committee chairs are circled in black, vice chairs are circled in a dotted black circle, and ranking members have four black lines around them.](./key-progress.png)
```

2020-09-15 17:18 UTC, Frijol commented on content/reports/reports-content.md
> +![A graphic demonstrating the House Energy & Commerce Committee: twenty four republican members and thirty one democrat members of the Senate Environment & Public Works Committee. Frank Palone is a d
```suggestion
![A graphic demonstrating the House Energy & Commerce Committee: twenty-four republican members and thirty-one democrat members of the Senate Environment & Public Works Committee. Frank Palone is a democrat and the chair, Yvette D. Clarke is a democrat and the vice chair, Greg Walden is a republican and a ranking member](house-energy-commerce.png)
```

2020-09-15 17:18 UTC, Frijol commented on content/reports/reports-content.md
> +![ to updt](./key-outlines.png)
incomplete?

2020-09-15 17:18 UTC, Frijol commented on content/reports/reports-content.md
>  ![](./key-progress.png)
this one needs alt text too!

2020-09-15 17:18 UTC, Frijol commented on content/reports/reports-content.md
> +![A key to the colors used in the graphic: republicans are in red circles and democrats in blue circles, lighter shaded circles indicate the report card is yet to be made, darker shaded circles indic
```suggestion
![A key to the colors used in the graphic: republicans are in red circles and democrats in blue circles, lighter shaded circles indicate the report card is yet to be made, darker shaded circles indicate the reportcard is in progress and circles with a green check indicate the report card is completed](./key-outlines.png)
```

2020-09-15 17:18 UTC, Frijol commented on content/reports/reports-content.md
> +![A key to the colors used in the graphic: republicans are in red circles and democrats in blue circles, lighter shaded circles indicate the report card is yet to be made, darker shaded circles indic
Can't add a space here, it will make the image fail to render

2020-09-15 17:19 UTC, Frijol commented
All of the "Republican" and "Democrat" designations should be capitalized as well

2020-09-17 02:20 UTC, lesliealanis commented
Hi @Frijol I'm not sure where to go from here, I made the edits you suggested and commit them directly to the branch I made.

2020-09-17 17:48 UTC, Frijol requested changes

2020-09-17 17:48 UTC, Frijol commented on content/reports/reports-content.md
> +![A graphic demonstrating the Senate Environment & Public Works Committee: eleven republican members and ten democrat members of the Senate Environment & Public Works Committee. John Barraso is a rep
It looks like these changes didn't get made, can you check please?

2020-09-27 19:42 UTC, Frijol requested changes

2020-09-27 19:42 UTC, Frijol commented on content/reports/reports-content.md
> +![A cycle diagram demonstrating how congress mandates EPA, the EPA issues and enforces permits to facilities that pollute, the ECHO database stores compliance data about these facilities, EEW makes E
```suggestion
![A cycle diagram demonstrating how Congress mandates EPA, the EPA issues and enforces permits to facilities that pollute, the ECHO database stores compliance data about these facilities, EEW makes ECHO data easier to understand and EEW works with communities to make environmental compliance report cards which pushes on congress to enforce environmental enforcement through the EPA](./report-card-tracker.png)
```

2020-09-27 19:42 UTC, Frijol commented on content/reports/reports-content.md
> +![A graphic demonstrating the Senate Environment & Public Works Committee: eleven Republican members and ten Democrat members of the Senate Environment & Public Works Committee. John Barraso is a Rep
```suggestion
![A graphic demonstrating the Senate Environment & Public Works Committee: eleven Republican members and ten Democrat members of the Senate Environment & Public Works Committee. John Barraso is a Republican and the chair, Thomas R. Carper is a Democrat and a ranking member](./senate-env-pw.png)
```

2020-09-27 19:42 UTC, Frijol commented on content/reports/reports-content.md
> +![A graphic demonstrating the House Energy & Commerce Committee: twenty-four Republican members and thirty-one Democrat members of the Senate Environment & Public Works Committee. Frank Palone is a D
```suggestion
![A graphic demonstrating the House Energy & Commerce Committee: twenty-four Republican members and thirty-one Democrat members of the Senate Environment & Public Works Committee. Frank Pallone is a Democrat and the chair, Yvette D. Clarke is a Democrat and the vice chair, Greg Walden is a Republican and a ranking member](house-energy-commerce.png)
```

2020-09-27 19:43 UTC, Frijol approved these changes

2020-09-27 19:43 UTC, merged